#!/usr/bin/expect

set timeout 15
set logenable [lindex $argv 0]
set Directory /home/evarima/lab/logs
log_user $logenable

set f [open iplist]
set ipadd [split [read -nonewline $f] "\n"]
close $f

# Iterate over the hosts
foreach host $ipadd {

        set SN [catch {exec snmpwalk -v2c -c P3mmzfKi $host 1.3.6.1.2.1.47.1.1.1.1.11.1 | grep -oP "(?<=\").*(?=\")"}]
        puts "$SN"
        sleep 1

}


puts "\n"
puts "\n"
puts "\n"

puts "================="
puts "Script completed"
puts "================="

exit
