#!/usr/bin/expect

set timeout 15
set snmpkey [lindex $argv 0]
set Username [lindex $argv 1]
set Password [lindex $argv 2]
set ctr1 0

set f [open iplist]
set ipadd [split [read -nonewline $f] "\n"]
close $f

foreach host $ipadd {
     set temp [catch {exec snmpwalk -v2c -c $snmpkey $host sysDescr | grep -oP "(?<=STRING: )\[^,\]*"}]
     if {$temp == 0 } {
          set HWMODEL [exec snmpwalk -v2c -c $snmpkey $host sysDescr | grep -oP "(?<=STRING: )\[^,\]*"]
     } else {
          set HWMODEL "N/A"
     }
     incr ctr1
     switch -regexp $HWMODEL  {
          NX-OS {
               set g [open commandsnexus]
               set commandsnxs [split [read -nonewline $g] "\n"]
               close $g
               spawn ssh -oStrictHostKeyChecking=no $Username@$host
               expect {
                    timeout { send_user "\nPUSH_FAILED\n"; break}
                    eof { send_user "\nPUSH_FAILED\n"; break}
                    "assword:" { send "$Password\r"}
               }
               # Iterate over the commands
               foreach cmd $commandsnxs {
                    expect {
                         "*#" {
                              send "$cmd\r"
                              sleep 1
                         }
                    }
               }
               expect {
                       "#" {send "exit\r"}
               }
               expect eof
          }
          IOS {
               set h [open commandscisco]
               set commandsios [split [read -nonewline $h] "\n"]
               close $h
               spawn ssh -oStrictHostKeyChecking=no $Username@$host
               expect {
                    timeout { send_user "\nPUSH_FAILED\n"; break}
                    eof { send_user "\nPUSH_FAILED\n"; break}
                    "assword:" { send "$Password\r"}
               }
               
               # Iterate over the commands
               foreach cmd $commandsios {
                    expect {
                         "*#" {
                              send "$cmd\r"
                              sleep 1
                         }
                    }
               }
               expect {
                    "#" {send "exit\r"}
               }
               expect eof
          }
          default {
               puts "$host is an UNKNOWN DEVICE"
          }
     }
}

puts "\n"
puts "\n"
puts "\n"

puts "================="
puts "Script completed"
puts "================="

exit
