#!/usr/bin/expect

#set debug [lindex $argv 0]
set timeout 10
set Directory /home/<path>/SCRIPTS/logs
set tdate [clock format [clock seconds] -format %Y-%h-%d_%H:%M:%S_ -timezone :Asia/Manila]
set FNAME Pinger_Result.txt
set LOGNAME "$Directory/$tdate$FNAME"

set Counter1 0
set Counter2 0

set f [open iplist]
set ipadd [split [read -nonewline $f] "\n"]
close $f

log_user 0

log_file $LOGNAME
send_log "IP Address\t\t\tStatus\n"
log_file

# Iterate over the hosts
foreach host $ipadd {

spawn ping -c3 -w2 $host
expect {
     "100% packet loss" {
          log_file $LOGNAME
          send_log "$host\t\t\tFAILED\n"
          log_file
          wait
          send_user "$host\t\tFAIL\n"
          incr Counter1
          }
     -re "\[0-9]% packet loss|\[0-9\]\[0-9\]% packet loss" {
          log_file $LOGNAME
          send_log "$host\t\t\tREACHABLE\n"
          log_file
          wait
          send_user "$host\t\tPASS\n"
          incr Counter2
          }
     }
}

wait

set total "[expr $Counter1+$Counter2]"

puts "\n"
puts "\n"
puts "\n"

puts "================="
puts "Script completed"
#puts "TOTAL Device tested: expr ($Counter1+$Counter2+$Counter3)"
puts "TOTAL Device tested: $total"
puts "UNREACHABLE: $Counter1"
puts "REACHABLE: $Counter2"
puts "================="

exit
