#!/usr/bin/bash

touch /home/evarima/lab/configs/out.txt       
echo -e "IP ADDRESS\t\tHOSTNAME\t\tIOS VERSION\t\tSOURCE INTERFACE\t\tSERIAL" >> /home/evarima/lab/out.txt
wait

while read line
do
        value=$line
        GETHOST=`snmpwalk -v2c -c P3mmzfKi $value sysName | grep -oP '(?<=STRING: )[^.]*' || echo "n/a"`
        wait
        GETIOS=`snmpwalk -v2c -c P3mmzfKi $value sysDescr | grep -oP '(?<=Version ).*(?= RELEASE)' || echo "n/a"`
        wait
        GETPREMGMT=`snmpwalk -v2c -c P3mmzfKi $value ipAdEntIfIndex.$value | grep -oP '(?<=INTEGER: )[^.]*' || echo "n/a"`
        wait
        GETMGMT=`snmpwalk -v2c -c P3mmzfKi $value ifDescr.$GETPREMGMT | grep -oP '(?<=STRING: )[^.]*' || echo "n/a"`   
        wait
        GETSERIAL=`snmpwalk -v2c -c P3mmzfKi $value 1.3.6.1.2.1.47.1.1.1.1.11.1 | grep -oP '(?<=").*(?=")' || echo "n/a"`
        wait
        echo -e "$value\t\t$GETHOST\t\t$GETIOS\t\t$GETMGMT\t\t$GETSERIAL" >> /home/evarima/lab/out.txt
        wait

done < testlist
wait

#sed -ri 's/^[[:blank:]]+//' /home/evarima/lab/configs/*
#wait

clear


echo ""
echo ""
echo "**************************************************"
echo                    "SCRIPT COMPLETED"
echo "**************************************************"






GET HOSTNAME:
snmpwalk -v2c -c P3mmzfKi 13.130.17.1 sysName | grep -oP '(?<=STRING: )[^.]*'
usa0105-campus-r01.network.corp.xerox.net

GET IOS:
snmpwalk -v2c -c P3mmzfKi 13.130.17.1 sysDescr | grep -oP '(?<=Version ).*(?= RELEASE)'
15.1(2)SY5,

GET MGMT INT:
snmpwalk -v2c -c P3mmzfKi 13.130.17.1 ipAdEntIfIndex.13.130.17.1 | grep -oP '(?<=INTEGER: )[^.]*'
117
snmpwalk -v2c -c P3mmzfKi 13.130.17.1 ifDescr.117 | grep -oP '(?<=STRING: )[^.]*'           
Loopback100

GET SERIAL:
snmpwalk -v2c -c P3mmzfKi 13.139.102.11 1.3.6.1.2.1.47.1.1.1.1.11 | grep -m1 "" | grep -oP '(?<=").*(?=")'
SAL16074EWJ

