#!/usr/bin/expect

set timeout 30
set username [lindex $argv 0]
set password [lindex $argv 1]
set snmpuser [lindex $argv 2]
set snmpkey [lindex $argv 3]
set stats [lindex $argv 4]
set uniQ [lindex $argv 5]
set Directory /home/$username/BackupCFG
set tdate [clock format [clock seconds] -format %Y-%h-%d_%H:%M:%S_ -timezone :Asia/Manila]
set FNAME $stats-CfgBackup_Result.txt

set CTRS 0
set CTRF 0
set TOTAL 0

set LOGNAME "/home/repos/public/iosup/logs/$tdate$FNAME"

log_user 0

set f [open /home/repos/public/.mimetool/iplist]
set ipadd [split [read -nonewline $f] "\n"]
close $f

log_file $LOGNAME
send_log "IP Address;Backup config\n"
log_file

send_user "IP ADDRESS\t\t\tSTATUS\n"

# Iterate over the hosts
foreach host $ipadd {

spawn scp -oStrictHostKeyChecking=no $username@$host:system:running-config $Directory/$stats-$uniQ-$host.cfg
   expect {
        timeout {send_user "$host\t\t\tFAIL\n"; incr CTRF}
            eof {send_user "$host\t\t\tFAIL\n"; incr CTRF}
        -re "assword" {send "$password\r"}
   }

   expect {
        timeout {log_file $LOGNAME
                 send_log "$host;Backup-Failed\n"
                 log_file
                 incr CTRF}
        -re "100%" {log_file $LOGNAME
                    send_log "$host;Backup-Success\n"
                    log_file
                    incr CTRS}
   }

#sleep .5
                                                                                                           
                                                                                                                         
send_user "$host\t\tCompleted\n"                                                                                         
}                                                                                                                        
                                                                                                                         
                                                                                                                         
set TOTAL "[expr $CTRS+$CTRF]"                                                                                           
                                                                                                                         
puts "\n"                                                                                                                
puts "\n"                                                                                                                
puts "\n"                                                                                                                
                                                                                                                         
puts "================="                                                                                                 
puts "Script completed"                                                                                                  
puts ""                                                                                                                  
puts "TOTAL Device tested: $TOTAL"                                                                                       
puts "Successful Backup: $CTRS"                                                                                          
puts "Failed Backup: $CTRF"                                                                                              
puts ""                                                                                                                  
puts "to goto folder where cfgs were saved: cd $Directory"                                                                    
puts "Paste the output to excel file using ';' as delimiter"                                                             
puts "================="
                                                                                                                         
exit    
