#!/usr/bin/expect

set timeout 15
set snmpkey [lindex $argv 0]
#set Password [lindex $argv 1]
set Directory /home/<path>
set tdate [clock format [clock seconds] -format %Y-%h-%d_%H:%M:%S_ -timezone :Asia/Manila]
set FNAME Source_Interface_Result.txt

set PCTR1 0
set PCTR2 0

set LOGNAME "$Directory/$tdate$FNAME"

log_user 0

set f [open iplist]
set ipadd [split [read -nonewline $f] "\n"]
close $f

log_file $LOGNAME
send_log "IP Address\t\tPing\t\tMgmt Int\n"
log_file

send_user "IP ADDRESS                STATUS\n"

# Iterate over the hosts
foreach host $ipadd {

spawn ping -c3 -w2 $host
expect {
     "100% packet loss" {
          log_file $LOGNAME
          send_log "$host\t\tFAILED\t\t"
          log_file
          incr PCTR2
     }
     -re "\[0-9]% packet loss|\[0-9\]\[0-9\]% packet loss" {
          log_file $LOGNAME
          send_log "$host\t\tPASSED\t\t"
          log_file
          incr PCTR1
     }
     }

##SEND IP ON LOG FILE
#log_file $LOGNAME
#send_log "$host\t\t"
#log_file
     
##GET MGMTINT
set temp3 [catch {exec snmpwalk -v2c -c $snmpkey $host ipAdEntIfIndex.$host | grep -oP "(?<=INTEGER: )\[^.\]*"}]
     if {$temp3 == 0 } {
          set IFINDX [exec snmpwalk -v2c -c $snmpkey $host ipAdEntIfIndex.$host | grep -oP "(?<=INTEGER: )\[^.\]*"]
          set MGMTINT [exec snmpwalk -v2c -c $snmpkey $host ifDescr.$IFINDX | grep -oP "(?<=STRING: )\[^.\]*"]
     } else {
          set MGMTINT "   N/A"
     }
     log_file $LOGNAME
     send_log "$MGMTINT\t\t"
     log_file

send_user "$host                Completed\n"
}

wait

set Ptotal "[expr $PCTR1+$PCTR2]"

puts "\n"
puts "\n"
puts "\n"

puts "================="
puts "Script completed"
puts "TOTAL Device tested: $Ptotal"
puts "PING SUCCESS: $PCTR1"
puts "PING FAILED: $PCTR2"
puts ""
puts "view log file thru cat $LOGNAME"
puts "================="

exit
