#!/usr/bin/expect

set timeout 15
log_user 0

set size_orig [match_max]
puts "Buffer size is: $size_orig"
puts ""

match_max 10000

set f [open iplist]
set ipadd [split [read -nonewline $f] "\n"]
close $f

foreach host $ipadd {

spawn ping -c3 $host
expect {
     "100% packet loss" {send_user "network device down\n"}
     -re "\[0-9]% packet loss|\[0-9\]\[0-9\]% packet loss" {send_user "network device up\n"}
}

puts ""
puts ""
puts ""

set output $expect_out(buffer)
#send_user "$output"

set parsed [regexp {\d+%\s.*} $output parsed1]
puts "Number of words: [regexp -all {[^ ]+} $output]"
#puts $parsed
puts $parsed1


puts ""
puts ""
puts ""

match_max $size_orig

}

exit


**************


#!/usr/bin/expect

expect_tty {
    one {send_user "one"}
    two {send_user "TWO"}
}

exit
