#!/usr/bin/expect

set timeout 10
set Directory /home/evarima/SCRIPTS/logs
set Username [lindex $argv 0]
set Password [lindex $argv 1]
set dibug [lindex $argv 2]
set CTRS 0
set CTRF 0

set f [open iplist]
set ipadd [split [read -nonewline $f] "\n"]
close $f

set g [open commands]
set commands [split [read -nonewline $g] "\n"]
close $g

log_user $dibug

log_file $Directory/wlc_push_result.txt
send_log "IP ADDRESS\t\tSTATUS\n"
log_file
wait

# Iterate over the hosts
foreach host $ipadd {

set LOGIN_STATUS [catch {
        spawn -noecho ssh -o ConnectTimeout=10 -oStrictHostKeyChecking=no -l test $host
        expect {
        timeout {return}
        eof {return}
        "*assword*:" {continue}
        "*ser*:" {continue}
    }}]

if {$LOGIN_STATUS == 4 } {
    log_file $Directory/$host
    spawn ssh -oStrictHostKeyChecking=no $Username@$host
    expect {
		"*ser:" {send "$Username\r"; exp_continue}
        "*assword:" {send "$Password\r"; exp_continue}
		"*>" {send "\r"}
    }
	
    # Iterate over the commands
    foreach cmd $commands {
        expect {
            "*>" {
                send "$cmd\r"
				#sleep 1
                 }
            }
        }

        expect {
                "*>" {send "logout\r"; exp_continue}
				"(y/N)" {send "n\r"}
        }
    log_file
	expect eof
		
	log_file $Directory/wlc_push_result.txt
    send_log "$host\t\tSUCCESS\n"
	log_file
	incr CTRS
	wait
} else {
	log_file $Directory/wlc_push_result.txt
    send_log "$host\t\tFAIL\n"
	log_file
	incr CTRF
	wait
    }

}

set total "[expr $CTRS+$CTRF]"

puts "\n"
puts "\n"
puts "\n"

puts "================="
puts "Riverbed MTO Script completed"
puts ""
puts "TOTAL Device in the list: $total"
puts "Config PUSH SUCCESS: $CTRS"
puts "Config PUSH FAILED: $CTRF"
puts ""
puts "view summary of push thru cat $Directory/wlc_push_result.txt"
puts "================="

exit
