#!/usr/bin/expect

set timeout 60
set Username [lindex $argv 0]
set Password [lindex $argv 1]
set Directory /home/<path>/SCRIPTS/logs

set f [open iplist]
set ipadd [split [read -nonewline $f] "\n"]
close $f

set g [open commands]
set commands [split [read -nonewline $g] "\n"]
close $g

# Iterate over the hosts
foreach host $ipadd {

        log_file $Directory/$host
        spawn ssh -oStrictHostKeyChecking=no $Username@$host
        expect {
                timeout { send_user "\nPUSH_FAILED\n"; break}
                eof { send_user "\nPUSH_FAILED\n"; break}
                "assword:" { send "$Password\r"}
        }

        # Iterate over the commands
        foreach cmd $commands {
                expect {
                        "*#" {
                                #sleep 1
                                send "$cmd\r"
                        }
                }
        }

        expect {
                "#" {send "exit\r"; send_user "\nPUSH_SUCCESS\n"}
        }

        expect eof
        log_file
}



puts "\n"
puts "\n"
puts "\n"

puts "================="
puts "Script completed"
puts "================="

exit
