#!/usr/bin/env python

import xlrd
path = "/home/ivan/API-TestExcel.xlsx"
book = xlrd.open_workbook(path)
sheet1 = book.sheet_by_index(0)

try:
    dlist = []
    for i in range(5, sheet1.nrows):
        dlist.append(sheet1.row_values(i))
    for i in range(len(dlist)):
        serialNumber = dlist[i][0]
        deviceName = dlist[i][1]
        startPort = dlist[i][2]
        endPort = dlist[i][3]
        portType = dlist[i][4]
        Vlan = dlist[i][5]
        print('Serial: {}, Name: {}, start: {}, end: {}, type: {}, vlan: {}'.format(serialNumber, deviceName, startPort, endPort, portType, Vlan))
except:
    pass
