#!/usr/bin/expect

set timeout 10
set tdate [clock format [clock seconds] -format %Y-%h-%d_%H:%M -timezone :Asia/Manila]

puts "time today is: $tdate\n"

exit



------

to incorporate it in existing scripts

set Directory /home/evarima/SCRIPTS/logs
set tdate [clock format [clock seconds] -format %Y-%h-%d_%H:%M:%S_ -timezone :Asia/Manila]
set FNAME Pinger_Result.txt

set LOGNAME "$Directory/$tdate$FNAME"

log_file $LOGNAME
send_log "IP Address\t\t\tStatus\n"
log_file
