#!/usr/bin/expect

set timeout 30
set username [lindex $argv 0]
set password [lindex $argv 1]
set snmpuser [lindex $argv 2]
set snmpkey [lindex $argv 3]
set stats [lindex $argv 4]
set uniQ [lindex $argv 5]
set Directory /home/repos/public/iosup/logs
set localdir /home/$username/showcmds
set tdate [clock format [clock seconds] -format %Y-%h-%d_%H:%M:%S_ -timezone :Asia/Manila]
set FNAME $stats-showcmds.txt

set LOGNAME "$Directory/$tdate$FNAME"

set CTRS 0
set CTRF 0

set f [open /home/repos/public/.mimetool/iplist]
set ipadd [split [read -nonewline $f] "\n"]
close $f

set g [open /home/repos/public/.mimetool/commands]
set commands [split [read -nonewline $g] "\n"]
close $g

# Iterate over the hosts
foreach host $ipadd {

set LOGIN_STATUS [catch {
     spawn ssh -o ConnectTimeout=10 -oStrictHostKeyChecking=no -l test $host
     expect {
        timeout {return}
        eof {return}
        -re "\[^ ]+assword:" {continue}
    }}]

if {$LOGIN_STATUS == 4 } {
    spawn ssh -oStrictHostKeyChecking=no $username@$host
    expect {
        "assword:" { send "$password\r"}
    }

    send "\r"
    send "\r"
    sleep 1

    log_file $localdir/$stats-$uniQ-show-$host

    # Iterate over the commands
    foreach cmd $commands {
        expect {
             -re "\[^ ]+#$" {send "$cmd\r"}
            }
        }

    expect {
         -re "\[^ ]+#$" {send "exit\r"}
        }
    log_file
    expect eof

    log_file $LOGNAME
    send_log "$host\t\tSUCCESS\n"
    log_file
    incr CTRS

} else {
    log_file $LOGNAME
    send_log "$host\t\tFAIL\n"
    log_file
    incr CTRF
    }

}

set total "[expr $CTRS+$CTRF]"

puts "\n"
puts "\n"
puts "\n"

puts "================="
puts "Script completed"
puts ""
puts "TOTAL Device in the list: $total"
puts ""
puts "view summary of push thru cat $LOGNAME"
puts "show outputs are stored on $localdir"
puts "================="

exit
