#!/bin/bash

#=======================================
#REMARKS
#TOOL CREATED FOR TW
#Will push command on cisco / riverbed
#procurve and comware devices
#COMPARE OUTPUT
tpath=/home/repos/public/.tools
hpath=/home/repos/public/.toolscript
spath=/home/repos/public/.mimetool
vpath=/home/repos/public/tool/toolscript
#push logs located /home/VzID/pushlogs
#=======================================


while :
do
clear
cat<<EOF
==============================
TW / WBros Alabang Tools
------------------------------
Option (1)Enter Credentials
Option (2)Populate Seedfile
Option (3)Populate Commands Seedfile
Option (4)Push Commands
       (Q)uit
------------------------------
EOF
tput bold
read -p "Enter your choice: " REPLY
tput sgr0
    case "$REPLY" in
    "1")
        clear
        echo "Please enter the VzID: "
        read VzID
        clear
        echo "Please enter the tacacs pw: "
        read tacacs
        clear
        echo "Please enter the enable"
        read enable
        clear
        echo "Saving Credentials..."
        sleep 2
        clear
        echo "Credentials saved. Please validate"
        echo ""
        echo "==============================="
        echo "VZID: $VzID"
        echo "TACACS: $tacacs"
        echo "Enable: $enable"
        echo "==============================="
        echo ""
        read -p "Hit enter if all are correct."

        fullPath=/home/$VzID/twtools/pushlogs
        clear
        if [ -d "$fullPath" ]
        then
             echo "Logs repository folder existing"
             sleep 1
             clear
        else 
		     mkdir /home/$VzID/twtools
		     mkdir /home/$VzID/twtools/pushlogs
             mkdir /home/$VzID/twtools/showcmds
             mkdir /home/$VzID/twtools/BackupCFG
             mkdir /home/$VzID/twtools/ReposCFG
             echo "Logs repository folder created"
             sleep 1
            clear
        fi
        ;;


    "2")
        clear
        echo "To edit press 'i' -- to save press esc and write ':wq' and hit enter"
		echo "input format should be Entityname:Devicetype (e.g.) twtur-e001:procurve"
        read -p "Hit enter to continue"
        touch /home/$VzID/twtools/iplist
        truncate -s 0 /home/$VzID/twtools/iplist
        vi /home/$VzID/twtools/iplist
        clear
        read -p "SeedFile Populated. Do you want to view seedfile? (y/n): " answer
        if [ "$answer" == "y" ] || [ "$answer" == "yes" ] || [ "$answer" == "Yes" ] || [ "$answer" == "Y" ] || [ "$answer" == "YES" ]
        then
           echo "============================================================================="
           echo ""
           cat /home/$VzID/twtools/iplist
           echo ""
           echo "============================================================================="
        else
           clear
        fi
        read -p "Hit enter to continue"
        ;;

    "3")
	    touch /home/$VzID/twtools/commandscisco
		touch /home/$VzID/twtools/commandsriverbed
		touch /home/$VzID/twtools/commandsprocurve
        while :
        do
        clear
cat<<EOF
==============================
TW / WBros Alabang Tools
------------------------------
Command Seedfile submenu:

Option (1)cisco
Option (2)procurve
Option (3)riverbed
Option (4)comware
       (R)eturn to top menu
------------------------------
EOF
tput bold
read -p "Enter your choice: " REPLY
tput sgr0
         case "$REPLY" in
            "1")
               clear
               echo "To edit press 'i' -- to save press esc and write ':wq' and hit enter"
		       echo "input format should be how you type it in the cli. Include config term and/or write mem if needed"
			   echo "IMPT NOTE: This is command file for CISCO device!!"
               read -p "Hit enter to continue"
               touch /home/$VzID/twtools/commandscisco
               truncate -s 0 /home/$VzID/twtools/commandscisco
               vi /home/$VzID/twtools/commandscisco
               clear
               read -p "SeedFile Populated. Do you want to view seedfile? (y/n): " answer2
               if [ "$answer2" == "y" ] || [ "$answer2" == "yes" ] || [ "$answer2" == "Yes" ] || [ "$answer2" == "Y" ] || [ "$answer2" == "YES" ]
               then
                  echo "============================================================================="
                  echo ""
                  cat /home/$VzID/twtools/commandscisco
                  echo ""
                  echo "============================================================================="
               else
                  clear
               fi
               read -p "Hit enter to continue"
               ;;
			 
			 "2")
               clear
               echo "To edit press 'i' -- to save press esc and write ':wq' and hit enter"
		       echo "input format should be how you type it in the cli. Include config term and/or write mem if needed"
			   echo "IMPT NOTE: This is command file for PROCURVE device!!"
               read -p "Hit enter to continue"
               touch /home/$VzID/twtools/commandsprocurve
               truncate -s 0 /home/$VzID/twtools/commandsprocurve
               vi /home/$VzID/twtools/commandsprocurve
               clear
               read -p "SeedFile Populated. Do you want to view seedfile? (y/n): " answer3
               if [ "$answer3" == "y" ] || [ "$answer3" == "yes" ] || [ "$answer3" == "Yes" ] || [ "$answer3" == "Y" ] || [ "$answer3" == "YES" ]
               then
                  echo "============================================================================="
                  echo ""
                  cat /home/$VzID/twtools/commandsprocurve
                  echo ""
                  echo "============================================================================="
               else
                  clear
               fi
               read -p "Hit enter to continue"
               ;;
			   
			 "3") echo "under construction" ;;
             "4") echo "under construction" ;;

             "R")  break                     ;;
             "r")  echo "case sensitive!!"   ;; 
              * )  echo "invalid option"     ;;
             esac
             sleep 1
             done
             ;;


    "4")
        clear
        read -p "Do you want to view commands to be pushed? (y/n): " answer4
        if [ "$answer4" == "y" ] || [ "$answer4" == "yes" ] || [ "$answer4" == "Yes" ] || [ "$answer4" == "Y" ] || [ "$answer4" == "YES" ]
        then
           echo "============================================================================="
		   echo "For CISCO:"
		   cat  /home/$VzID/twtools/commandscisco
		   echo ""
		   echo ""
           echo "For PROCURVE:"
           cat /home/$VzID/twtools/commandsprocurve
           echo ""
           echo "============================================================================="
        else
           clear
        fi
		read -p "continue with push? (y/n): " answer5
        if [ "$answer5" == "y" ] || [ "$answer5" == "yes" ] || [ "$answer5" == "Yes" ] || [ "$answer5" == "Y" ] || [ "$answer5" == "YES" ]
        then
            echo ""
            echo "Starting configuration push..."
            echo ""
            sleep 1
            $spath/.twpush.sh $VzID $tacacs $enable
            wait
            echo ""
        else
           echo "Not proceeding with push. Returning to Main Menu"
        fi
        echo ""
        read -p "Hit enter to continue"
        ;;



    "Q") 
          clear
          echo ""                                                                                    
          echo "====================================================================="               
          echo ""                                                                                    
          echo "                               NOTE !!!                              "                
          echo "Session log files are located on BackupCFG, DiffCFG, showcmds Folders"                
          echo "Please note you'll need to transfer session files only if            "
          echo "You're done running pre and post tools                               "
          echo "Otherwise please choose NO.                                          "
          echo ""                                                                                    
          echo "====================================================================="  
          echo ""
          echo "Do you want to transfer all session files to local repository (y/n)"
          read answer
          if [ "$answer" == "y" ] || [ "$answer" == "yes" ] || [ "$answer" == "Yes" ] || [ "$answer" == "Y" ] || [ "$answer" == "YES" ]
          then
		                 mv /home/$VzID/twtools/pushlogs/* /home/$VzID/twtools/ReposCFG/
                         mv /home/$VzID/twtools/BackupCFG/* /home/$VzID/twtools/ReposCFG/
                         mv /home/$VzID/twtools/DiffCFG/* /home/$VzID/twtools/ReposCFG/
                         mv /home/$VzID/twtools/showcmds/* /home/$VzID/twtools/ReposCFG/
                      elif [ "$answer" == "n" ] || [ "$answer" == "N" ] || [ "$answer" == "no" ] || [ "$answer" == "No" ] || [ "$answer" == "NO" ]
                      then
             echo "Press enter to continue"    
                         read tempo10
                      else
                         echo "incorrect answer. Please answer with y or n only"
                         break
                      fi
          
          echo "Exiting the script.."
          echo "For any issues encountered please let me know"
          echo "Email me at mark.ivan.evaristo@intl.verizon.com"
          sleep 2
          exit
          ;;


    "q")  echo "case sensitive!!"   ;; 
     * )  echo "invalid option"     ;;
    esac
    sleep 1
done
